mag_ng/APIs/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from rest_framework.urlpatterns import format_suffix_patterns

from . import views

urlpatterns = [
    path('', views.api_root),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('users/', views.UserList.as_view(), name='user-list'),
    path('profile/<int:pk>/', views.Profile.as_view(), name='profile'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('article/', views.ArticleList.as_view(), name='articles'),
    path('article/<int:pk>/', views.ArticleDetail.as_view(), name='article-detail'),
    path('search/', views.SearchList.as_view(), name='search'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

mag_ng/articles/urls.py
from django . urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('create/', views.ArticleCreateView.as_view(), name='create'),
    path('write/<int:form_id>/', views.write_view, name='write'),
    path('edit/<int:pk>/', views.ArticleUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', views.ArticleDeleteView.as_view(), name='delete'),
    path('publish/<int:form_id>/', views.publish, name='publish'),
    path('detail/<int:pk>/', views.ArticleDetailView.as_view(), name='detail'),
    path('preview/<int:pk>/', views.PreviewView.as_view(), name='preview'),
    path('draft/', views.DraftView.as_view(), name='draft'),
    path('category/<category>/', views.CategoryView.as_view(), name='category'),
    path('recent/', views.RecentView.as_view(), name='recent'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('covid/', views.covid, name='covid')
]

mag_ng/mag_ng/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('articles.urls')),
    path('user/', include('users.urls')),
    path('api/', include('APIs.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='users/reset.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/reset_done.html'), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/reset_confirm.html'), name='password_reset_confirm'),
    path('password_reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/reset_complete.html'), name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mag_ng/users/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'users'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html', redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/<int:pk>/', views.Profile.as_view(), name='profile'),
    path('edit/', views.edit, name='edit'),
]

mag_ng/users/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.utils import timezone
from django.utils.text import slugify
from django.utils. translation import gettext_lazy as _
from PIL import Image
from django.core.files.storage import default_storage as storage

from .managers import CustomUserManager


class CustomUser(AbstractBaseUser, PermissionsMixin):
    #User model with granular control

    email = models.EmailField(_('email address'), unique=True)
    # first_name = models.CharField(_('first name'), max_length=20)
    username = models.CharField(_('username'), max_length=20, unique=True)
    slug = models.SlugField(default='slug')
    is_staff = models.BooleanField(_('staff'),default=False)
    is_active = models.BooleanField(_('active'),default=True)
    date_joined = models.DateTimeField(_('date joined'), auto_now_add=True)
    last_login = models.DateTimeField(_('last login'), auto_now=True)
    avatar = models.ImageField(upload_to='avatars', default='default.jpg', blank=True, null=True)
    bio = models.TextField(_('Bio'), blank=True, null=True)
    social_handle = models.CharField(_('Twitter/Instagram handle'), max_length=15, blank=True, null=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    objects = CustomUserManager()

    def __str__(self):
        # full_name = '%s %s' %(self.first_name, self.last_name)
        return self.username

    def get_email(self):
        return self.email

    def save(self, *args, **kwargs):
        self.slug = slugify(self.email)
        super(CustomUser, self).save()

        img = Image.open(self.avatar)

        if img.height > 514 or img.width > 534:
            output_size = (514, 534)
            img.thumbnail(output_size)
            # img.save(self.avatar.path)
            fh = storage.open(self.avatar.name, "w")
            picture_format = 'png'
            img.save(fh, picture_format)
            fh.close()

mag_ng/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.db import transaction
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
   
    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('email', 'username')


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('email', 'username', 'avatar', 'bio', 'social_handle',)

    @transaction.atomic
    def save(self, *args, **kwargs):
        user = super().save(commit=False)
        user.is_guest = True
        user.save()
        return user

mag_ng/users/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from django.views.generic import DetailView
from django.contrib.auth import get_user_model
from django.contrib import messages
from articles.models import ArticleModel
from .forms import CustomUserChangeForm
from .forms import CustomUserCreationForm
from django.contrib.auth.decorators import login_required

User = get_user_model()


def signup(request):
    if request.user.is_authenticated:
        return redirect('articles:home')
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            user.save()
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(email=user.email, password=raw_password)
            # login(request, user)
            messages.success(request,f'Your account has been created, you\'re now able to log in.')
            return redirect('users:login')
    else:
        form = CustomUserCreationForm()
    return render(request, 'users/signup.html', {'form': form, 'title': 'Sign-Up'})


class Profile(DetailView):
    model = User
    template_name = 'users/profile.html'
    context_object_name = 'object'
    slug_field = 'slug'
    slug_url_kwarg = 'user'
    query_pk_and_slug = True

    def get_queryset(self, **kwargs):
        return User.objects.get(pk=self.kwargs['pk'])

    def get_object(self, **kwargs):
        return User.objects.get(pk=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['count'] = ArticleModel.objects.filter(publish=True, author=self.get_object()).count()
        context['articles'] = ArticleModel.objects.filter(publish=True, author=self.get_object()).order_by('-date_posted')
        context['title'] = 'Profile'
        return context


@login_required
def edit(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, f'You acccount has been updated')
            return redirect('users:profile', pk=request.user.id)
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form,
        'title': 'Edit Profile'
    }
    return render(request, 'users/update_profile.html', context)

mag_ng/users/templates/users/login.html
{% extends "articles/base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
    <main>
        <form id="login" method="POST" action="">
                {% csrf_token %}
                <legend>Login</legend>
                {{ form|crispy }}
                <div class="btn-submit">
                        <input type="submit" value="LOG IN" />
                </div>
                <div class="social">
                        <span class="socialtext">OR SIGN IN WITH</span>
                        <div class="socialicons">
                                <span class="iconitem">
                                        <img src="{% static 'users/assets/facebook.svg' %}" alt="facebook icon"/>
                                </span>
                                    <span class="iconitem">
                                            <img src="{% static 'users/assets/pinterest.svg' %}" alt="twitter icon"/>
                                    </span>
                            <span class="iconitem">
                                    <img src="{% static 'users/assets/twitter.svg' %}" alt="pinterest icon"/>
                            </span>
                        </div>
                </div>
                <div class="signin">
                  <p>DON'T HAVE AN ACCOUNT YET?</p>
                  <p>CLICK HERE TO <a href="{% url 'users:signup' %}" id="signuplink">SIGN UP</a></p>
                    <p>Forgot Password? <a href="{% url 'password_reset' %}" id="signuplink">Click here</a></p>
                </div>
        </form>
    </main>
{% endblock content %}

mag_ng/users/templates/users/logout.html
{% extends "articles/base.html" %}
{% block content %}
    <div class="container">
        <h2>You have been logged out</h2>
        <div class="border-top pt-3">
            <small class="text-muted">
                <a href="{% url 'users:login' %}">Log In Again</a>
            </small>
        </div>
    </div>
{% endblock content %}

mag_ng/users/templates/users/profile.html
{% extends "articles/base.html" %}
{% load crispy_forms_tags %}
{% load custom_filter_tags %}
{% load static %}
{% block content %}
    <div class="user_profile d-flex justify-content-between">
        <div class="d-flex profile_card-right">
            <div class="profile_img_cover">
                <img src="{{ object.avatar.url }}" alt="">
            </div>
            <div class="ml-lg-4 ml-md-3 ml-sm-2 ml-1">
                <h6 class="profile_name">{{ object.username }}</h6>
                <p class="membership">Membership Since : <span>{{ object.date_joined }}</span></p>
                <p class="profile_details">{{ count }} Articles</p>
                <p class="profile_details">Email: {{ object.email }}</p>
                {% if object.social_handle %}
                <p class="profile_details">Twitter: <a href="https://twitter.com/{{ object.social_handle }}" target="_blank">{{ object.social_handle }}</a></p>
                {% endif %}
                {% if user == object %}
                <div>
                    <a href="{% url 'articles:draft' %}">My Drafts</a>
                </div>
                {% endif %}
                {% if object.bio %}
                 <p class="profile-details">Bio: {{ object.bio }}</p>
                {% endif%}
            </div>
        </div>
        {% if user == object %}
        <div>
            <a href="{% url 'users:edit' %}"><i class='bx bxs-cog'></i></a>
        </div>
        {% endif %}
    </div>

    <div class="page_title_container">
        {% if user == object %}
        <h3 class="page_title text-center">YOUR ARTICLES</h3>
        {% else %}
        <h3 class="page_title text-center">Articles by {{ object.username }}</h3>
        {% endif %}

    </div>

    <section id="top_magazine">

        <div class="magazine_grid">
            {% for article in articles %}
             <a href="{% url 'articles:detail' article.id %}">
            <div class="magazine_card">
                <div class="magazine_img_cover">
                    {% if article.cover_image %}
                    <img src="{{ article.cover_image.url }}" alt="">
                    {% endif %}
                </div>
                <div class="magazine_card_content">
                    <span class="magazine_title">{{ article.categories }}</span>
                    <h6>{{ article.title|shrink }}...</h6>
                    <p class="time">{{ article.date_posted|date:"F d, Y" }}</p>
                </div>
            </div>
                </a>
            {% endfor %}
        </div>
    </section>
{% endblock content %}

mag_ng/users/templates/users/reset.html
{% extends "articles/base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
		<main>
       		<form id="signup" method="POST">
				{% csrf_token %}
         		<legend>FORGOT PASSWORD</legend>

          		{{ form }}

            	<div class="btn-submit">
            		<input type="submit" value="SUBMIT" />
            	</div>	
        	</form>
    	</main>
{% endblock content %}

mag_ng/users/templates/users/reset_complete.html
{% extends "articles/base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-8 col-sm-12">
                <div class="alert alert-info">
                    Your password has been set
                </div>
                <a href="{% url 'users:login' %}">Sign in here</a>
            </div>
        </div>
        <div class="col"></div>
    </div>
{% endblock %}

mag_ng/users/templates/users/reset_confirm.html
{% extends "articles/base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
		<main>
       		<form id="signup" method="POST">
				{% csrf_token %}
         		<legend>RESET PASSWORD</legend>

          		{{ form }}

            	<div class="btn-submit">
            		<input type="submit" value="SUBMIT" />
            	</div>	
        	</form>
    	</main>
{% endblock content %}

mag_ng/users/templates/users/reset_done.html
{% extends "articles/base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-8 col-sm-12">
                <div class="alert alert-info">
                    An email has been sent with instructions to reset your password
                </div>
            </div>
        </div>
        <div class="col"></div>
    </div>
{% endblock %}

mag_ng/users/templates/users/signup.html
{% extends "articles/base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
        <main>
        <form id="login" method="POST" action="">
                {% csrf_token %}
                <legend>Sign Up</legend>
                {{ form|crispy }}
                <div class="btn-submit">
                        <input type="submit" value="SIGN UP" />
                </div>
                <span class="terms"
          >By registering, you accept our
          <a href="http://">terms and conditions</a>
        </span>
                <div class="social">
                        <span class="socialtext">OR SIGN UP WITH</span>
                        <div class="socialicons">
                                <span class="iconitem">
                                        <img src="{% static 'users/assets/facebook.svg' %}" alt="facebook icon"/>
                                </span>
                                    <span class="iconitem">
                                            <img src="{% static 'users/assets/pinterest.svg' %}" alt="twitter icon"/>
                                    </span>
                            <span class="iconitem">
                                    <img src="{% static 'users/assets/twitter.svg' %}" alt="pinterest icon"/>
                            </span>
                        </div>
                </div>
                <div class="signin">
                  <p>ALREADY HAVE AN ACCOUNT?</p>
                  <p>CLICK HERE TO <a href="{% url 'users:login' %}" id="signuplink">SIGN IN</a></p>
                </div>
        </form>
            </main>
{% endblock content %}

mag_ng/users/templates/users/update_profile.html
{% extends "articles/base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
   <div class="user_profile d-flex justify-content-between">
        <div class="d-flex profile_card-right">
            <div class="profile_img_cover">
                <img src="{{ user.avatar.url }}" alt="">
            </div>
            <div class="ml-lg-4 ml-md-3 ml-sm-2 ml-1">
                <h6 class="profile_name">{{ user.username }}</h6>
                <p class="membership">Membership Since : <span>{{ user.date_joined }}</span></p>
                <p class="profile_details">Email: {{ user.email }}</p>
                {% if user.social_handle %}
                <p class="profile_details">Twitter: <a href="https://twitter.com/{{ user.social_handle }}" target="_blank">{{ user.social_handle }}</a></p>
                {% endif %}
                {% if user.bio %}
                 <p class="profile-details">Bio: {{ user.bio }}</p>
                {% endif%}
            </div>
        </div>
    </div>
       <div class="container-fluid">
        <div class="row">
            <div class="col"></div>
            <div class="col-md-8 col-sm-12">
                <form method="POST" action="" enctype="multipart/form-data" class="mt-5">
        <legend class="border-bottom mb-4">Edit Profile</legend>
            {% csrf_token %}
            <fieldset class="form-group">
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Save</button>
            </div>
        </form>
            </div>
            <div class="col"></div>
        </div>
    </div>
{% endblock content %}