mag_ng/APIs/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from rest_framework.urlpatterns import format_suffix_patterns

from . import views

urlpatterns = [
    path('', views.api_root),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('users/', views.UserList.as_view(), name='user-list'),
    path('profile/<int:pk>/', views.Profile.as_view(), name='profile'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('article/', views.ArticleList.as_view(), name='articles'),
    path('article/<int:pk>/', views.ArticleDetail.as_view(), name='article-detail'),
    path('search/', views.SearchList.as_view(), name='search'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

mag_ng/articles/urls.py
from django . urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('create/', views.ArticleCreateView.as_view(), name='create'),
    path('write/<int:form_id>/', views.write_view, name='write'),
    path('edit/<int:pk>/', views.ArticleUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', views.ArticleDeleteView.as_view(), name='delete'),
    path('publish/<int:form_id>/', views.publish, name='publish'),
    path('detail/<int:pk>/', views.ArticleDetailView.as_view(), name='detail'),
    path('preview/<int:pk>/', views.PreviewView.as_view(), name='preview'),
    path('draft/', views.DraftView.as_view(), name='draft'),
    path('category/<category>/', views.CategoryView.as_view(), name='category'),
    path('recent/', views.RecentView.as_view(), name='recent'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('covid/', views.covid, name='covid')
]

mag_ng/mag_ng/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('articles.urls')),
    path('user/', include('users.urls')),
    path('api/', include('APIs.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='users/reset.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/reset_done.html'), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/reset_confirm.html'), name='password_reset_confirm'),
    path('password_reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/reset_complete.html'), name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mag_ng/users/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'users'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html', redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/<int:pk>/', views.Profile.as_view(), name='profile'),
    path('edit/', views.edit, name='edit'),
]

mag_ng/articles/models.py
from django.db import models
#from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.utils import timezone
from datetime import datetime, timedelta

User = get_user_model()


def default_start_time():
    now = datetime.now()
    start = now.replace(hour=22, minute=0, second=0, microsecond=0)
    return start if start > now else start + timedelta(days=1)


categories_choices = (
    ('Art & Architecture', 'Art & Architecture'),
    ('Boating & Aviation', 'Boating & Aviation'),
    ('Business & Finance', 'Business & Finance'),
    ('Cars & Motorcycles', 'Cars & Motorcycles'),
    ('Celebrity & Gossip', 'Celebrity & Gossip'),
    ('Comics & Manga', 'Comics & Manga'),
    ('Crafts', 'Crafts'),
    ('Culture & Literature', 'Culture & Literature'),
    ('Family & Parenting', 'Family & Parenting'),
    ('Fashion', 'Fashion'),
    ('Food & Wine', 'Food & Wine'),
    ('Health & Fitness', 'Health & Fitness'),
    ('Home & Garden', 'Home & Garden'),
    ('Hunting & Fishing', 'Hunting & Fishing'),
    ('Kids & Teen', 'Kids & Teen'),
    ('Luxury', 'Luxury'),
    ('Men\'s Lifestyle', 'Men\'s Lifestyle'),
    ('Movies, Tv & Music', 'Movies, Tv & Music'),
    ('News & Politics', 'News & Politics'),
    ('Photography', 'Photography'),
    ('Science & Engineering', 'Science & Engineering'),
    ('Sports', 'Sports'),
    ('Tech & Gaming', 'Tech & Gaming'),
    ('Travel & Outdoor', 'Travel & Outdoor'),
    ('Women\'s Lifestyle', 'Women\'s Lifestyle'),
    ('Adult +18', 'Adult +18'),
)


class ArticleModel(models.Model):
    title = models.CharField(max_length=255)
    cover_image = models.ImageField(blank=True, null=True, upload_to='images/')
    description = models.TextField(blank=True, null=True)
    author = models.ForeignKey(User, default=1, on_delete=models.CASCADE)
    date_posted = models.DateTimeField(default=timezone.now)
    publish = models.BooleanField(default=False)
    categories = models.CharField(max_length=50, choices=categories_choices, default='fashion')
    objects = models.Manager()

    def __str__(self):
        return self.title


class ImageModel(models.Model):
    article = models.ForeignKey(ArticleModel, default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/')
    image_description = models.TextField(blank=True, null=True)
    timestamp = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.article.title


class TextModel(models.Model):
    article = models.ForeignKey(ArticleModel, default=None, on_delete=models.CASCADE)
    header = models.CharField(max_length=255, null=True, blank=True)
    text = models.TextField()
    timestamp = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.article.title

mag_ng/articles/views.py
import os
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import ArticleModel, ImageModel, TextModel
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.forms import inlineformset_factory
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden, Http404
from django.contrib import messages
from itertools import chain
import random
from django.db.models import Q
from .apis import search
api_key = os.getenv('api_key')


class HomeView(ListView):
    model = ArticleModel
    template_name = 'articles/home.html'
    context_object_name = 'fashion'
    ordering = ['-date_posted']

    # def get_queryset(self):
    #     return ArticleModel.objects.filter(publish=True)

    def get_context_data(self, **kwargs):
        db_size = ArticleModel.objects.count()
        if db_size == 0:
            random_list = 0
        elif db_size == 1 :
            random_list = 0
        elif db_size == 2:
            random_list = 2
        elif db_size == 3:
            random_list = 3
        elif db_size == 4:
            random_list = 4
        elif db_size == 5:
            random_list = 5
        else:
            random_list = random.sample(range(db_size), 5)

        context = super().get_context_data(**kwargs)
        context['fashion'] = list(ArticleModel.objects.filter(publish=True, categories='Fashion').order_by(
            '-date_posted')[:5])
        context['business'] = list(ArticleModel.objects.filter(publish=True, categories='Business & Finance').order_by(
            '-date_posted')[:5])
        context['science'] = list(ArticleModel.objects.filter(publish=True, categories='Science & Engineering').order_by(
            '-date_posted')[:5])
        context['recent'] = list(ArticleModel.objects.filter(publish=True).order_by(
            '-date_posted')[:5])
        context['recommended'] = list(ArticleModel.objects.filter(id__in=random_list, publish=True))
        context['title'] = 'Home'
        return context


class ArticleCreateView(LoginRequiredMixin, CreateView):
    model = ArticleModel
    fields = ['title', 'cover_image', 'description', 'categories']
    template_name = 'articles/create_article.html'

    def get_success_url(self):
        user_latest_article = ArticleModel.objects.all().filter(author=self.request.user).last()
        return reverse('articles:write', kwargs={'form_id': user_latest_article.id})

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Create'
        return context


@login_required
def write_view(request, form_id):
    article = get_object_or_404(ArticleModel, pk=form_id)
    if request.user != article.author:
        return HttpResponseForbidden()
    image_formset = inlineformset_factory(ArticleModel, ImageModel, fields=('image', 'image_description', ), extra=1)
    text_formset = inlineformset_factory(ArticleModel, TextModel, fields=('header', 'text', ), extra=1)
    formset_1 = image_formset(instance=article)
    formset_2 = text_formset(instance=article)
    if request.method == 'POST':
        formset_1 = image_formset(request.POST, request.FILES, instance=article)
        formset_2 = text_formset(request.POST, instance=article)
        if formset_2.is_valid() and formset_1.is_valid():
            formset_1.save()
            formset_2.save()
            return redirect('articles:write', form_id=form_id)
    context = {
        'article': article,
        'form_1': formset_1,
        'form_2': formset_2,
        'title': 'Write'
    }
    return render(request, 'articles/write.html', context)


class ArticleUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = ArticleModel
    fields = ['title', 'cover_image', 'description', 'categories']
    template_name = 'articles/edit_article.html'

    def get_success_url(self):
        article = self.get_object()
        return reverse('articles:write', kwargs={'form_id': article.id})

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        article = self.get_object()
        if self.request.user == article.author:
            return True
        return False

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Update'
        return context


class ArticleDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = ArticleModel
    template_name = 'articles/delete_article.html'
    context_object_name = 'object'
    success_url = '/'

    def test_func(self):
        article = self.get_object()
        if self.request.user == article.author:
            return True
        return False

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Delete'
        return context


@login_required
def publish(request, form_id):
    article = get_object_or_404(ArticleModel, pk=form_id)
    if request.user != article.author:
        return HttpResponseForbidden()
    if not article.publish:
        article.publish = True
        article.save()
    messages.success(request, 'Your article has been published')
    return redirect('articles:home')


class ArticleDetailView(DetailView):
    model = ArticleModel
    template_name = 'articles/detail.html'
    context_object_name = 'object'
    queryset = ArticleModel.objects.filter(publish=True)

    def sort(self):
        article = self.get_object()
        images = article.imagemodel_set.all()
        text_contents = article.textmodel_set.all()
        combine = list(chain(images, text_contents))
        for i in range(len(combine)-1):
            min_pos = i
            for j in range(i, len(combine)):
                if combine[j].timestamp < combine[min_pos].timestamp:
                    min_pos = j
            combine[i], combine[min_pos] = combine[min_pos], combine[i]
        return combine

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        obj = self.get_object()
        context['main_content'] = self.sort()
        context['more'] = ArticleModel.objects.filter(author=obj.author, publish=True).order_by('-date_posted')[:5]
        context['title'] = 'Article'
        return context


class PreviewView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = ArticleModel
    template_name = 'articles/preview.html'
    context_object_name = 'object'

    def sort(self):
        article = self.get_object()
        images = article.imagemodel_set.all()
        text_contents = article.textmodel_set.all()
        combine = list(chain(images, text_contents))
        for i in range(len(combine)-1):
            min_pos = i
            for j in range(i, len(combine)):
                if combine[j].timestamp < combine[min_pos].timestamp:
                    min_pos = j
            combine[i], combine[min_pos] = combine[min_pos], combine[i]
        return combine

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['main_content'] = self.sort()
        context['title'] = 'Preview'
        return context

    def test_func(self):
        article = self.get_object()
        if self.request.user == article.author:
            return True
        return False


class DraftView(LoginRequiredMixin, ListView):
    model = ArticleModel
    template_name = 'articles/draft.html'
    context_object_name = 'objects'
    ordering = ['-date_posted']

    def get_queryset(self):
        return ArticleModel.objects.filter(publish=False, author=self.request.user).order_by('-date_posted')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Draft'
        return context


class CategoryView(ListView):
    model = ArticleModel
    template_name = 'articles/category.html'
    context_object_name = 'objects'
    ordering = ['-date_posted']

    def get_queryset(self):
        return ArticleModel.objects.filter(publish=True, categories=self.kwargs.get('category')).order_by('-date_posted')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = self.kwargs.get('category')
        context['title'] = self.kwargs.get('category')
        return context


class RecentView(ListView):
    model = ArticleModel
    template_name = 'articles/category.html'
    context_object_name = 'objects'
    ordering = ['-date_posted']

    def get_queryset(self):
        return ArticleModel.objects.filter(publish=True).order_by('-date_posted')[:25]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = 'Recently Added'
        context['title'] = 'Recent'
        return context


class SearchView(ListView):
    model = ArticleModel
    template_name = 'search_view.html'
    context_object_name = 'objects'

    def get_queryset(self):
        query = self.request.GET.get('q')
        article_list = ArticleModel.objects.filter(
            Q(title__icontains=query) | Q(author__icontains=query, publish=True)
        )
        return article_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = self.request.GET.get('q')
        context['title'] = 'Search'
        return context


def covid(request):
    query = request.POST.get('search')
    res = search(1, 30, 'covid 19', api_key)
    context = {
        'articles': res,
        'query': query
    }

mag_ng/articles/templates/articles/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% if title %}
    <title>Mag-Ng | {{ title }}</title>
    {% else %}
    <title>Mag-Ng</title>
    {% endif %}
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">
    <!-- Main Stylesheet -->
    <link rel="stylesheet" type="text/css" href="{% static 'articles/css/landing.css' %}">
    <!-- Bootstrap Stylesheet -->
    <link rel="stylesheet" href="{% static 'articles/css/bootstrap.min.css' %}">
    <!-- Box Icons -->
    <link href='https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css' rel='stylesheet'>
    <!-- AOS Library Stylesheet -->
    <link rel="stylesheet" href="{% static 'articles/css/aos.css' %}">
<!--    <link rel="stylesheet" href="{% static 'articles/css/navigation.css' %}">-->
    <link rel="stylesheet" href="{% static 'articles/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'articles/css/sign_up.css' %}">
</head>

<body>
    <!-- Page Preloader -->
    <div class="loader">
        <div class="w-25">
            <img src="{% static 'articles/images/logo.png' %}" class="mx-auto" alt="">
        </div>
        <div class="lds-roller">
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>
    <!-- End of Page Preloader -->

    <!-- Scroll to top button -->
    <button onclick="topFunction()" id="myBtn" title="Scroll to top">
        <i class='bx bx-up-arrow-alt'></i>
    </button>

    <nav class="navbar navbar-expand-sm navbar-dark nav_bar-new mb-5 fixed">
        <a class="navbar-brand" href="{% url 'articles:home' %}"><img src="{% static 'articles/images/logo.png' %}" alt=""></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main_nav"
            aria-expanded="false" aria-label="Toggle navigation">
            <i class='bx bx-menu' style="color:black;"></i>
        </button>
        <div class="collapse navbar-collapse" id="main_nav">
            <ul class="navbar-nav">
                <li class="nav-item active"> <a class="nav-link" href="{% url 'articles:covid' %}">COVID 19 UPDATES</a> </li>
            </ul>

            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown has-megamenu">
                    <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">MAGAZINES</a>
                    <div class="dropdown-menu megamenu ml-auto" role="menu">
                        <h6 class="title">CATEGORIES</h6>
                        <div class="row">
                                <div class="col-md-3 col-6">
                                    <div class="col-megamenu">
                                        <ul class="list-unstyled">
                                            <li><a href="{% url 'articles:category' 'Art & Architecture' %}">Art & Architecture</a></li>
                                            <li><a href="{% url 'articles:category' 'Celebrity & Gossip' %}">Celebrity & Gossip</a></li>
                                            <li><a href="{% url 'articles:category' 'Family and Parenting' %}">Family and Parenting</a></li>
                                            <li><a href="{% url 'articles:category' 'Home and Garden' %}">Home and Garden</a></li>
                                            <li><a href="{% url 'articles:category' 'Men\'s Lifestyle' %}">Men's Lifestyle</a></li>
                                            <li><a href="{% url 'articles:category' 'Science & Engineering' %}">Science & Engineering</a></li>
                                            <li><a href="{% url 'articles:category' 'Women\'s Livestyle' %}">Women's Livestyle</a></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="col-md-3 col-6">
                                    <div class="col-megamenu">
                                        <ul class="list-unstyled">
                                            <li><a href="{% url 'articles:category' 'Boating & Aviation' %}">Boating & Aviation</a></li>
                                            <li><a href="{% url 'articles:category' 'Comics & Manga' %}">Comics & Manga</a></li>
                                            <li><a href="{% url 'articles:category' 'Fashion' %}">Fashion</a></li>
                                            <li><a href="{% url 'articles:category' 'Hunting & Fishing' %}">Hunting & Fishing</a></li>
                                            <li><a href="{% url 'articles:category' 'Movies, TV & Music' %}">Movies, TV & Music</a></li>
                                            <li><a href="{% url 'articles:category' 'Sports' %}">Sports</a></li>
                                            <li><a href="{% url 'articles:category' 'Adult +18' %}">Adult +</a></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="col-md-3 col-6">
                                    <div class="col-megamenu">
                                        <ul class="list-unstyled">
                                            <li><a href="{% url 'articles:category' 'Business & Finance' %}">Business & Finance</a></li>
                                            <li><a href="{% url 'articles:category' 'Crafts' %}">Crafts</a></li>
                                            <li><a href="{% url 'articles:category' 'Food & Wine' %}">Food & Wine</a></li>
                                            <li><a href="{% url 'articles:category' 'Kids & Teens' %}">Kids & Teens</a></li>
                                            <li><a href="{% url 'articles:category' 'News & Politics' %}">News & Politics</a></li>
                                            <li><a href="{% url 'articles:category' 'Tech & Gaming' %}">Tech & Gaming</a></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="col-md-3 col-6">
                                    <div class="col-megamenu">
                                        <ul class="list-unstyled">
                                            <li><a href="{% url 'articles:category' 'Cars & Motocycles' %}">Cars & Motocycles</a></li>
                                            <li><a href="{% url 'articles:category' 'Culture & Literature' %}">Culture & Literature</a></li>
                                            <li><a href="{% url 'articles:category' 'Health & Fitness' %}">Health & Fitness</a></li>
                                            <li><a href="{% url 'articles:category' 'Luxury' %}">Luxury</a></li>
                                            <li><a href="{% url 'articles:category' 'Photography' %}">Photography</a></li>
                                            <li><a href="{% url 'articles:category' 'Travel & Outdoor' %}">Travel & Outdoor</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        <h6 class="title mt-lg-5 mt-md-3 mt-2">FEATURED</h6>
                        <div class="row">

                            <div class="col-md-3 col-6">
                                <div class="col-megamenu">
                                    <ul class="list-unstyled">
                                        <li><a href="#">Most Popular</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-md-3 col-6">
                                <div class="col-megamenu">
                                    <ul class="list-unstyled">
                                        <li><a href="{% url 'articles:recent' %}">Recently Added</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-md-3 col-6">
                                <div class="col-megamenu">
                                    <ul class="list-unstyled">
                                        <li><a href="#">Newsletters & info.</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'users:profile' user.id %}">MY LIBRARY</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'articles:create' %}">CREATE</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'users:logout' %}">LOGOUT</a></li>
                    {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'users:login' %}">SIGN IN</a></li>
                    <li class="nav-item"><a class="nav-link" id="sign_up" href="{% url 'users:signup' %}">SIGN UP</a></li>
                    {% endif %}

            </ul>
        </div>
    </nav>
    <div class="container">
            <div class="row">
                <div class="col"></div>
                <div class="col-md-6 col-sm-12">
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-{{ message.tags }}">
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}
                </div>
                <div class="col"></div>
            </div>
        </div>
   {% block content %}
    {% endblock %}

    <footer id="main_footer">
        <div class="footer_top">
            <div class="footer_grid">
                <div class="">
                    <div class="d-flex flex-column">
                        <div class="logo_cover">
                            <img src="{% static 'articles/images/logo.png' %}" alt="">
                        </div>
                        <form action="">
                            <p>For Updates, Newsletters and other info</p>
                            <div class="position-relative">
                                <input type="email" class="form-control" id="email_sub" placeholder="Email">
                                <button class="subscribe_button position-absolute">
                                    Submit
                                </button>
                            </div>
                        </form>

                    </div>
                </div>
                <div class="">
                    <div class="d-flex flex-column">
                        <h3>COMPANY</h3>
                        <a>Careers</a>
                        <a>News</a>
                        <a>About</a>
                    </div>
                </div>
                <div class="">
                    <div class="d-flex flex-column">
                        <h3>RESOURCES</h3>
                        <a>Faqs</a>
                        <a>Contact Support</a>
                        <div class="d-flex">
                            <span class="d-flex">
                                <a href="" class="icons"><i class='bx bxl-facebook'></i></a>
                                <a href="" class="icons mx-2"><i class='bx bxl-twitter'></i></a>
                                <a href="" class="icons"><i class='bx bxl-pinterest-alt'></i></a>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="">
                    <div class="d-flex flex-column">
                        <div class="app_img">
                            <img src="{% static 'articles/images/google_app.png' %}" alt="">
                        </div>
                        <div class="app_img mt-1">
                            <img src="{% static 'articles/images/app.png' %}" alt="">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer_bottom d-flex justify-content-between">
            <div>
                <p>&copy; 2020 MagNg - All rights reserved UI Design by <span class="designer"></span></p>
            </div>
            <div class="d-flex">
                <a href="">Privacy</a>
                <a href="" class="mx-3">Cookies</a>
                <a href="">Terms</a>
            </div>
        </div>
    </footer>

     <script src="{% static 'articles/javascript/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'articles/javascript/popper.js' %}"></script>
    <script src="{% static 'articles/javascript/bootstrap.min.js' %}"></script>
    <script src="{% static 'articles/javascript/landing.js' %}"></script>
    <script src="{% static 'articles/javascript/aos.js' %}"></script>
</body>
</html>

mag_ng/articles/templates/articles/create_article.html
{% extends "articles/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col"></div>
            <div class="col-md-8 col-sm-12">
                <form method="POST" action="" enctype="multipart/form-data" class="mt-5">
        <legend class="border-bottom mb-4">Create Article</legend>
            {% csrf_token %}
            <fieldset class="form-group">
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Save and Continue</button>
            </div>
        </form>
            </div>
            <div class="col"></div>
        </div>
    </div>


{% endblock content %}

mag_ng/articles/templates/articles/draft.html
{% extends "articles/base.html" %}
{% block content %}
        <div class="row">
            <div class="col"></div>
            <div class="col-md-8 col-sm-12">
                {% if not objects %}
                <h2>You have no drafts</h2>
                {% else %}
                <legend class="border-bottom mb-4">Your Draft</legend>
                {% for article in objects %}
                    <div class="row border-bottom pt-5">
                        <div class="col-12">
                            <h2>{{ article.title }}</h2>
                            {% if article.description %}
                                <p><span class="text-muted">{{ article.description }}</span> </p>
                            {% endif %}
                            <a href="{% url 'articles:edit' article.id %}" class="btn btn-info mt-3 mb-3">continue editing</a>
                            <a href="{% url 'articles:delete' article.id %}" class="btn btn-danger mt-3 mb-3">delete</a>
                        </div>
                    </div>
                {% endfor %}
                {% endif %}
            </div>
            <div class="col"></div>
        </div>
{% endblock content %}